"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var tweet_controller_1 = require("../controllers/tweet.controller");
var auth_middleware_1 = require("../middlewares/auth.middleware");
var multer_middleware_1 = require("../middlewares/multer.middleware");
var router = (0, express_1.Router)();
router.use(auth_middleware_1.verifyJWT);
router.route("/").post(multer_middleware_1.upload.single("image"), tweet_controller_1.createTweet);
router.route("/user/:userId").get(tweet_controller_1.getUserTweets);
router.route("/:tweetId").patch(tweet_controller_1.updateTweet).delete(tweet_controller_1.deleteTweet);
router.route("/vote/:tweetId/:optionIndex").patch(tweet_controller_1.voteOnTweetPoll);
exports.default = router;
